[package]
name = "primality"
version = "0.1.0"
edition = "2021"

[dependencies]
divan = "0.1.14"
array2d = "0.3.2"
num = "0.4"
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
num-format = "0.4.4"
num-traits = "0.2.19"
rug = "1.24.1"

[[bench]]
name = "example"
harness = false

