[package]
name = "bigint_solovay"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4"
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
num-format = "0.4.4"
num-iter = "0.1.45"
rug = {version = "1.24.1", features=["num-traits"]}