[package]
name = "rho_table"
version = "0.1.0"
edition = "2021"

[dependencies]
chashmap = "2.2.2"
evmap = "10.0.2"
mod_exp = "1.0.1"
num = "0.4.3"
num-prime = "0.4.4"
rayon = "1.10.0"

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "hashmap_bench"
harness = false